application:
  language: ru
  country: RU

spring:
  datasource:
    url: jdbc:mysql://localhost/library?serverTimezone=Europe/Moscow
    username: otus
    password: javaclub
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    schema: schema.sql
    data: data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
      format_sql: true

shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED