application:
  language: ru
  country: RU
  object-not-found-message: "Object with Uid=%s not found!"

spring:
  datasource:
    url: jdbc:mysql://localhost/library?serverTimezone=Europe/Moscow
    username: otus
    password: javaclub
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  messages:
    basename: messages
    encoding: UTF-8

shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED