GET http://localhost:8080/api/v1/books
Accept: application/json

###
GET http://localhost:8080/api/v1/books/5e5adf297993217644371001
Accept: application/json

###

POST http://localhost:8080/v1/api/books
Content-Type: application/json

{
  "title": "The Brand New Book",
  "isbn": 12345678910,
  "publicationYear": 2019
}

###

PUT http://localhost:8080/api/v1/books/24
Content-Type: application/json

{
  "uid": 24,
  "title": "The Brand New Book (edited)",
  "isbn": 10987654321,
  "publicationYear": 2020
}

###

DELETE http://localhost:8080/api/v1/books/5e5ae05545b44b06f0b0a019
Content-Type: application/json

###
GET http://localhost:8080/api/v1/authors
Accept: application/json

###
GET http://localhost:8080/api/v1/genres
Accept: application/json

###
GET http://localhost:8080/api/v1/comments/book/15
Accept: application/json

###
