server:
  port: 8082

eureka:
  client:
    fetch-registry: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalog
      username: otus
      password: javaclub
      authentication-database: admin
  rabbitmq:
    username: otus
    password: javaclub
logging:
  level:
    root: INFO

application:
  rabbit:
    exchange: "main.exchange"
    queues:
      levels:
        catalog: "master.levels.catalog"
      prices:
        catalog: "master.prices.catalog"
      users:
        catalog: "users.stocks.catalog"