spring:
  rabbitmq:
    username: otus
    password: javaclub
  mail:
    host: smtp.gmail.com
    port: 587
    username: '{cipher}e5528fdcb2ac010804df7ebcceb6bb8222a2df7861ef3b9e3d2b5bb663d71ad588063e63bb279acfa4a3a42ee2f57b4b'
    password: '{cipher}e4d8b62bb110dfbce5980e302bd01c16a1c477b8079c4379c33c26724d78bf3cbe58cd438e45623c8f3980940b30ca29'
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

application:
  shop-id: 1001
  rabbit:
    exchanges:
      main: "main.topic"
      status: "status.broadcast"
    queues:
      products:
        orders-to-mail: "mail.status"
      users:
        name: "order.user.name"
