server:
  port: 8083

eureka:
  client:
    fetch-registry: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders-microservice
      username: otus
      password: javaclub
      authentication-database: admin
  rabbitmq:
    username: otus
    password: javaclub
logging:
  level:
    root: INFO

application:
  shop-id: 1001
  rabbit:
    exchanges:
      main: "main.topic"
      status: "status.broadcast"
    queues:
      levels:
        orders: "master.levels.orders"
      prices:
        orders: "master.prices.orders"
      products:
        proposal: "proposal.order"
        order: "order.proposal"
