server:
  port: 8082

eureka:
  client:
    fetch-registry: true

application:
  language: ru
  country: RU
  object-not-found-message: "Object with Uid=%s not found!"
  anonymous-comments-only: true

spring:
  datasource:
    url: jdbc:mysql://localhost/library?serverTimezone=Europe/Moscow
    username: otus
    password: javaclub
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    initialization-mode: never
#    schema: classpath:schema.sql
#    data: classpath:data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  messages:
    basename: messages
    encoding: UTF-8