drop table tbl_book_author if exists;
drop table tbl_book_genre if exists;
drop table tbl_book_comment if exists;

drop table tbl_authors if exists;
drop table tbl_books if exists;
drop table tbl_genres if exists;

drop table tbl_comments if exists;
drop table tbl_commentators if exists;

create table tbl_authors (uid bigint generated by default as identity, full_name varchar(255) not null, pen_name varchar(255), primary key (uid));
create table tbl_book_author (book_uid bigint not null, author_uid bigint not null);
create table tbl_book_genre (book_uid bigint not null, genre_uid bigint not null);
create table tbl_books (uid bigint generated by default as identity, isbn bigint, publication_year integer, title varchar(255) not null, primary key (uid));
create table tbl_genres (uid bigint generated by default as identity, name varchar(255) not null, primary key (uid));
alter table tbl_authors add constraint UC_full_name unique (full_name);
alter table tbl_books add constraint UC_title unique (title);
alter table tbl_genres add constraint UC_name unique (name);
alter table tbl_book_author add constraint FK_book_author_author FOREIGN KEY (author_uid) REFERENCES tbl_authors (uid) ON DELETE CASCADE ON UPDATE CASCADE;
alter table tbl_book_author add constraint FK_book_author_book FOREIGN KEY (book_uid) REFERENCES tbl_books (uid) ON DELETE CASCADE ON UPDATE CASCADE;
alter table tbl_book_genre add constraint fk_book_genre_book FOREIGN KEY (book_uid) REFERENCES tbl_books (uid) ON DELETE CASCADE ON UPDATE CASCADE;
alter table tbl_book_genre add constraint fk_book_genre_genre FOREIGN KEY (genre_uid) REFERENCES tbl_genres (uid) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE tbl_commentators (uid bigint(20) NOT NULL AUTO_INCREMENT,login varchar(50) NOT NULL,password varchar(20) DEFAULT NULL,first_name varchar(100) DEFAULT NULL,last_name varchar(100) DEFAULT NULL,PRIMARY KEY (uid));
ALTER TABLE tbl_commentators ADD CONSTRAINT UN_tbl_commentators UNIQUE KEY (login);

CREATE TABLE tbl_comments (uid bigint(20) NOT NULL AUTO_INCREMENT,commentator_uid bigint(20) NOT NULL,comment_text text NOT NULL,comment_date datetime NOT NULL,PRIMARY KEY (uid));
alter table tbl_comments add constraint FK_tbl_comments FOREIGN KEY (commentator_uid) REFERENCES tbl_commentators (uid) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE tbl_book_comment (book_uid bigint(20) NOT NULL,comment_uid bigint(20) NOT NULL);
alter table tbl_book_comment add constraint FK_book_comments FOREIGN KEY (book_uid) REFERENCES tbl_books (uid) ON DELETE CASCADE ON UPDATE CASCADE;
alter table tbl_book_comment add constraint FK_comments_book FOREIGN KEY (comment_uid) REFERENCES tbl_comments (uid) ON DELETE CASCADE ON UPDATE CASCADE;