version: "3.7"

services:
        database:
                image: mariadb
                container_name: hw17-database
                tty: true
                restart: always
                volumes:
                  - /tmp/docker_db_data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: strongpassword
                        MYSQL_DATABASE: library
                        MYSQL_USER: otus
                        MYSQL_PASSWORD: javaclub
                ports:
                  - "13306:3306"
        backend:
                container_name: hw17-backend
                build: backend/
                command: java -jar ./target/homework-10-1.0.jar
                ports:
                        - 8080:8080
                environment:
                        SPRING_APPLICATION_JSON: '{"spring": {"datasource": {"url": "jdbc:mysql://hw17-database:3306/library?serverTimezone=Europe/Moscow"}}}'
                depends_on:
                        - database
        frontend:
                container_name: hw17-frontend
                build: frontend/
                command: npm start
                ports:
                        - 4200:4200