version: "3"

services:
        backend:
                container_name: hw17-backend
                build: backend/
                command: java -jar ./target/homework-10-1.0.jar
                ports:
                        - 8080:8080
                environment:
                        # Используется база данных хоста. По требованию к
                        # ДЗ "БД в собственный контейнер оборачивать не нужно
                        # (если только Вы не используете кастомные плагины)"
                        #
                        # Не очень гибкое решение, но host.docker.internal
                        # работет если только host Windows или Mac.
                        # Для Linux не работает, а у меня как раз Linux
                        SPRING_APPLICATION_JSON: '{"spring": {"datasource": {"url": "jdbc:mysql://172.17.0.1/library?serverTimezone=Europe/Moscow"}}}'
        frontend:
                container_name: hw17-frontend
                build: frontend/
                command: npm start
                ports:
                        - 4200:4200