application:
  language: en
  country: EN

spring:
  datasource:
    url: jdbc:mysql://localhost/library?serverTimezone=Europe/Moscow
    username: otus
    password: javaclub
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    schema: schema.sql
    data: data.sql
shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED