INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (3, 'The Hunger Games', 9780439023480, 2008);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (4, 'Harry Potter and the Philosophers Stone', 9780439554930, 1997);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (5, 'Twilight', 9780316015840, 2005);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (6, 'To Kill a Mockingbird', 9780061120080, 1960);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (7, 'The Great Gatsby', 9780743273560, 1925);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (8, 'The Fault in Our Stars', 9780525478810, 2012);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (9, 'The Hobbit or There and Back Again', 9780618260300, 1937);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (10, 'The Catcher in the Rye', 9780316769170, 1951);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (11, 'Angels & Demons ', 9781416524790, 2000);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (12, 'Pride and Prejudice', 9780679783270, 1813);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (13, 'The Kite Runner ', 9781594480000, 2003);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (14, 'Divergent', 9780062024040, 2011);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (15, 'Nineteen Eighty-Four', 9780451524940, 1949);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (16, 'Animal Farm: A Fairy Story', 9780452284240, 1945);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (17, 'Het Achterhuis: Dagboekbrieven 14 juni 1942 - 1 augustus 1944', 9780553296980, 1947);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (18, 'Män som hatar kvinnor', 9780307269750, 2005);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (19, 'Catching Fire', 9780439023500, 2009);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (20, 'Harry Potter and the Prisoner of Azkaban', 9780439655480, 1999);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (21, ' The Fellowship of the Ring', 9780618346260, 1954);
INSERT INTO tbl_books (uid, title, isbn, publication_year) VALUES (22, 'Mockingjay', 9780439023510, 2010);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (31, 'Suzanne Collins', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (32, 'Joanne Rowling', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (33, ' Mary GrandPré', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (34, 'Stephenie Meyer', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (35, 'Harper Lee', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (36, 'Scott Fitzgerald', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (37, 'John Green', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (38, 'John Tolkien', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (39, 'Jerome Salinger', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (40, 'Dan Brown', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (41, 'Jane Austen', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (42, 'Khaled Hosseini', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (43, 'Veronica Roth', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (44, 'George Orwell', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (45, 'Erich Fromm', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (46, 'Celâl Üster', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (48, 'Anne Frank', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (49, 'Eleanor Roosevelt', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (50, 'Barbara Mooyaart-Doubleday', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (51, 'Stieg Larsson', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (55, 'Reg Keeland', null);
INSERT INTO tbl_authors (uid, full_name, pen_name) VALUES (56, 'Rufus Beck', null);
INSERT INTO tbl_genres (uid, name) VALUES (1, 'Dystopian');
INSERT INTO tbl_genres (uid, name) VALUES (2, 'Science fiction');
INSERT INTO tbl_genres (uid, name) VALUES (3, 'Fantasy');
INSERT INTO tbl_genres (uid, name) VALUES (4, 'Romance');
INSERT INTO tbl_genres (uid, name) VALUES (5, 'Young adult fiction');
INSERT INTO tbl_genres (uid, name) VALUES (6, 'Southern Gothic');
INSERT INTO tbl_genres (uid, name) VALUES (7, 'Bildungsroman');
INSERT INTO tbl_genres (uid, name) VALUES (8, 'Tragedy');
INSERT INTO tbl_genres (uid, name) VALUES (9, 'Realistic fiction');
INSERT INTO tbl_genres (uid, name) VALUES (10, 'High fantasy');
INSERT INTO tbl_genres (uid, name) VALUES (11, 'Juvenile fantasy');
INSERT INTO tbl_genres (uid, name) VALUES (12, 'Coming-of-age fiction');
INSERT INTO tbl_genres (uid, name) VALUES (13, 'Action');
INSERT INTO tbl_genres (uid, name) VALUES (14, 'Mystery');
INSERT INTO tbl_genres (uid, name) VALUES (15, 'Thriller');
INSERT INTO tbl_genres (uid, name) VALUES (16, 'Classic Regency novel');
INSERT INTO tbl_genres (uid, name) VALUES (17, 'Historical fiction');
INSERT INTO tbl_genres (uid, name) VALUES (18, 'Drama');
INSERT INTO tbl_genres (uid, name) VALUES (19, 'Classic');
INSERT INTO tbl_genres (uid, name) VALUES (20, 'Political fiction');
INSERT INTO tbl_genres (uid, name) VALUES (21, 'Political satire');
INSERT INTO tbl_genres (uid, name) VALUES (22, 'Autobiography');
INSERT INTO tbl_genres (uid, name) VALUES (23, 'Crime');
INSERT INTO tbl_genres (uid, name) VALUES (24, 'Scandinavian noir');
INSERT INTO tbl_genres (uid, name) VALUES (25, 'War');
INSERT INTO tbl_genres (uid, name) VALUES (26, 'Adventure');
INSERT INTO tbl_roles (uid, name) VALUES (1, 'ADMIN');
INSERT INTO tbl_roles (uid, name) VALUES (2, 'USER');

INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (38, 15, 45);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (39, 4, 33);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (40, 18, 55);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (41, 17, 48);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (42, 17, 50);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (43, 11, 40);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (44, 17, 49);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (45, 15, 44);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (46, 16, 44);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (47, 6, 35);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (48, 12, 41);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (49, 10, 39);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (50, 4, 32);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (51, 20, 32);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (37, 15, 46);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (52, 8, 37);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (53, 9, 38);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (54, 21, 38);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (55, 13, 42);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (56, 20, 55);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (57, 20, 56);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (58, 7, 36);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (59, 5, 34);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (60, 18, 51);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (61, 3, 31);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (62, 19, 31);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (63, 22, 31);
INSERT INTO tbl_book_author (uid, book_uid, author_uid) VALUES (64, 14, 43);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (96, 3, 1);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (97, 14, 1);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (98, 15, 1);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (99, 19, 1);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (100, 3, 2);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (101, 14, 2);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (102, 15, 2);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (103, 19, 2);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (104, 22, 2);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (105, 4, 3);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (106, 5, 3);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (107, 20, 3);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (108, 21, 3);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (109, 5, 4);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (110, 5, 5);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (111, 8, 5);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (112, 14, 5);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (113, 6, 6);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (114, 6, 7);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (115, 7, 8);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (116, 8, 9);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (117, 10, 9);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (118, 9, 10);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (119, 9, 11);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (120, 10, 12);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (121, 11, 13);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (122, 22, 13);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (123, 11, 14);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (124, 18, 14);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (125, 11, 15);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (126, 18, 15);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (127, 22, 15);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (128, 12, 16);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (129, 13, 17);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (130, 13, 18);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (131, 13, 19);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (132, 15, 20);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (133, 16, 21);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (134, 17, 22);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (135, 18, 23);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (136, 18, 24);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (137, 22, 25);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (138, 3, 26);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (139, 19, 26);
INSERT INTO tbl_book_genre (uid, book_uid, genre_uid) VALUES (140, 22, 26);

INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (1, 'ac1', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '1 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (2, 'ac2', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '2 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (3, 'ac3', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '3 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (4, 'ac4', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '4 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (5, 'ac5', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '5 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (6, 'ac6', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '6 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (7, 'ac7', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '7 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (8, 'ac8', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '8 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (9, 'ac9', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '9 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (10, 'ac10', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '10 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (11, 'ac11', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '11 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (12, 'ac12', '$2a$04$oT48FfqTQkUeFca4Rh6y6O6ugG1KUBl9OcYK1S.wgu5XJ15heXAwe', '12 Angry', 'Commentator');
INSERT INTO tbl_users (uid, username, password, first_name, last_name) VALUES (13, 'admin', '$2a$04$0wTIwF27gN3rY6tBU8Bl0uIi4z2MNb16XaHO/q.s7klvXJxkXeKzi', 'Angry', 'Administrator');

INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (14, 3, 1, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (15, 4, 2, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (16, 5, 3, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (17, 6, 4, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (18, 7, 5, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (19, 8, 6, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (20, 9, 7, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (21, 10, 8, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (22, 11, 9, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (23, 12, 10, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (24, 13, 11, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (25, 14, 12, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (26, 15, 12, 'An angry comment', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (27, 3, 1, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (28, 4, 2, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (29, 5, 3, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (30, 6, 4, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (31, 7, 5, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (32, 8, 6, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (33, 9, 7, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (34, 10, 8, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (35, 11, 9, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (36, 12, 10, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (37, 13, 11, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (38, 14, 12, 'An angry comment 2', '2020-01-11 22:29:00');
INSERT INTO tbl_comments (uid, book_uid, user_uid, comment_text, comment_date) VALUES (39, 15, 12, 'An angry comment 2', '2020-01-11 22:29:00');

INSERT INTO tbl_user_role (uid, user_uid, role_uid) VALUES (1, 3, 2);
INSERT INTO tbl_user_role (uid, user_uid, role_uid) VALUES (2, 13, 1);
INSERT INTO tbl_user_role (uid, user_uid, role_uid) VALUES (3, 13, 2);

